import { MarkerType } from '@xyflow/react';

const microservices = {
  id: 'microservices',
  name: 'Microservices Architecture',
  description: 'API Gateway with multiple services, database, and message queue',
  category: 'backend',
  nodes: [
    {
      id: 'node-1',
      type: 'architectureNode',
      position: { x: 100, y: 250 },
      data: {
        label: 'API Gateway',
        nodeType: 'api',
        color: '#10b981',
        icon: 'A',
      },
    },
    {
      id: 'node-2',
      type: 'architectureNode',
      position: { x: 450, y: 80 },
      data: {
        label: 'User Service',
        nodeType: 'service',
        color: '#6366f1',
        icon: 'S',
      },
    },
    {
      id: 'node-3',
      type: 'architectureNode',
      position: { x: 450, y: 250 },
      data: {
        label: 'Order Service',
        nodeType: 'service',
        color: '#6366f1',
        icon: 'S',
      },
    },
    {
      id: 'node-4',
      type: 'architectureNode',
      position: { x: 450, y: 420 },
      data: {
        label: 'Notification Service',
        nodeType: 'service',
        color: '#6366f1',
        icon: 'S',
      },
    },
    {
      id: 'node-5',
      type: 'architectureNode',
      position: { x: 800, y: 160 },
      data: {
        label: 'PostgreSQL',
        nodeType: 'database',
        color: '#f59e0b',
        icon: 'D',
      },
    },
    {
      id: 'node-6',
      type: 'architectureNode',
      position: { x: 800, y: 370 },
      data: {
        label: 'Redis Queue',
        nodeType: 'queue',
        color: '#8b5cf6',
        icon: 'Q',
      },
    },
  ],
  edges: [
    {
      id: 'edge-1-2',
      source: 'node-1',
      target: 'node-2',
      label: 'auth & user routes',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
    {
      id: 'edge-1-3',
      source: 'node-1',
      target: 'node-3',
      label: 'order routes',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
    {
      id: 'edge-1-4',
      source: 'node-1',
      target: 'node-4',
      label: 'notification routes',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
    {
      id: 'edge-2-5',
      source: 'node-2',
      target: 'node-5',
      label: 'user queries',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
    {
      id: 'edge-3-5',
      source: 'node-3',
      target: 'node-5',
      label: 'order queries',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
    {
      id: 'edge-3-6',
      source: 'node-3',
      target: 'node-6',
      label: 'order events',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
    {
      id: 'edge-6-4',
      source: 'node-6',
      target: 'node-4',
      label: 'notification triggers',
      animated: true,
      style: { stroke: '#e94560', strokeWidth: 2 },
      markerEnd: { type: MarkerType.ArrowClosed, color: '#e94560' },
    },
  ],
  nodeMetadata: {
    'node-1': {
      description: 'Central API Gateway that routes requests to appropriate microservices. Handles authentication, rate limiting, and request routing.',
      files: [],
      directory: '',
      status: 'not_started',
      buildPrompt: 'Create an API Gateway using Express.js with route proxying to downstream services. Include JWT authentication middleware, rate limiting, request logging, and health check endpoints.',
    },
    'node-2': {
      description: 'Handles user registration, authentication, profile management, and authorization.',
      files: [],
      directory: '',
      status: 'not_started',
      buildPrompt: 'Create a User Service with Express.js. Include user registration, login with JWT tokens, profile CRUD operations, and password hashing with bcrypt. Connect to PostgreSQL for user data.',
    },
    'node-3': {
      description: 'Manages order lifecycle: creation, updates, status tracking, and order history.',
      files: [],
      directory: '',
      status: 'not_started',
      buildPrompt: 'Create an Order Service with Express.js. Include order CRUD operations, status management (pending, confirmed, shipped, delivered), and publish order events to Redis queue for downstream processing.',
    },
    'node-4': {
      description: 'Sends notifications via email, SMS, or push based on system events consumed from the message queue.',
      files: [],
      directory: '',
      status: 'not_started',
      buildPrompt: 'Create a Notification Service that consumes events from Redis queue. Support email (nodemailer), and in-app notification channels. Include notification templates and delivery status tracking.',
    },
    'node-5': {
      description: 'Shared PostgreSQL database with separate schemas per service for data isolation.',
      files: [],
      directory: '',
      status: 'not_started',
      buildPrompt: 'Set up PostgreSQL with separate schemas for users and orders. Create migration files for each schema. Include connection pooling configuration and database seeding scripts.',
    },
    'node-6': {
      description: 'Redis-based message queue for asynchronous event-driven communication between services.',
      files: [],
      directory: '',
      status: 'not_started',
      buildPrompt: 'Set up Redis as a message queue using BullMQ. Create queue definitions for order events and notification jobs. Include retry logic, dead letter queues, and queue monitoring.',
    },
  },
};

export default microservices;
